site_name: Student Manager Documentation
site_url: https://www.studentmanager.co.za
repo_url: https://github.com/AgileSystemsTechnology/StudentManager.Docs
site_favicon: favicon.ico

pages:
- Home: index.md

   
- People:
    - Adding People: People/adding-people.md
    - System Access: People/systemaccess.md
    - Account Activation Link: People/sendanaccountactivationlink.md
    - Assign Roles : People/assignroles.md
    - Change Student Status: People/changestatusofstudent.md
    - De-enrolling a Student: People/de-enrollingastudent.md
    - Change a Student Number: People/changeastudentnumber.md
    - Change a Qualification: People/changeaqualification.md

- Modules:
    - Add a Module: Modules/addamodule.md
    - Linking Modules to Qualifications: Modules/linkingmodulestoqualifications.md
    - Copy Module Groups in Bulk: Modules/copymodulegroupsinbulk.md
    - Moving Modules: Modules/movingmodules.md
    - Setting up Module Groups: Modules/settingupmodulegroups.md
    - Setting up Assessments: Modules/settingupassessments.md
    - Copy Assessments in Bulk: Modules/copyassessmentsinbulk.md

- Grading: 
    - Grade: Modules/grading.md
    - Online Tests: Modules/onlinetests.md
    - Assign Roles to Assessor or Lecturer: Modules/assignrolestoassessororlecturer.md

    - Reports:
    - Print a Lecture Time Table: Reports/printalecturetimetable.md
    - Print a Student Card: Reports/printingastudentcard.md
    - Printing Academic Transcripts: Reports/printingacademictranscripts.md

    - Leads:
    - Setting up Workflow Steps and Rules : Leads/settingupworkflowstepsandrules.md
    - Convert Lead to Student: Leads/convertleadtostudent.md
    
    
    - More:
    - Creating and Moving Logs: More/creatingandmovinglogs.md
    - Grade and Symbol Settings: More/gradeandsymbolsettings.md
    - Setting up Level Groupings: More/settinguplevelgroupings.md
    - Setting Telephone Numbers: More/settingtelephonenumbers.md
    - Switch off Autogenerated Student Numbers: More/switchoffautogeneratedstudentnumbers.md
    - Setting Student Fees: More/settingstudentfees.md
    - Send Bulk Activation Links: More/sendbulkactivationlinks.md
    
theme: readthedocs